In [1]:
%config ZMQInteractiveShell.ast_node_interactivity='all'

In [2]:
import tensorflow as tf
print(tf.__version__)

2.1.0


In [3]:
x = tf.constant(range(12))
x
x.shape
len(x)

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

TensorShape([12])

12

In [4]:
x = tf.reshape(x, (3,4))
x
x.shape

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

TensorShape([3, 4])

In [5]:
x = tf.constant(range(12))
x = tf.reshape(x, (-1,4))
x

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [6]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [7]:
tf.ones((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [8]:
tf.constant([[1,2,3],[4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [9]:
X = tf.reshape(x,(3,4))
X
Y = tf.constant([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
Y

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])>

In [23]:
X+Y

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 2,  2,  6,  6],
       [ 5,  7,  9, 11],
       [12, 12, 12, 12]])>

In [24]:
X * Y

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  8,  9],
       [ 4, 10, 18, 28],
       [32, 27, 20, 11]])>

In [25]:
Y = tf.cast(Y, tf.float32)
tf.exp(Y)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 7.389056 ,  2.7182817, 54.598152 , 20.085537 ],
       [ 2.7182817,  7.389056 , 20.085537 , 54.598152 ],
       [54.59815  , 20.085537 ,  7.389056 ,  2.7182817]], dtype=float32)>

In [30]:
Y
X
tf.transpose(Y)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])>

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[2, 1, 4],
       [1, 2, 3],
       [4, 3, 2],
       [3, 4, 1]])>

In [28]:
Y = tf.cast(Y, tf.int32)
tf.matmul(X, )

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 18,  20,  10],
       [ 58,  60,  50],
       [ 98, 100,  90]])>

In [32]:
x = tf.constant([[1,2,3],[4,5,6]])
y = tf.constant([[10,20,30],[40,50,60]])
x
y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]])>

In [35]:
tf.concat([x, y], axis=0)
tf.concat([x, y], axis=1)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])>

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])>

In [36]:
tf.equal(x, y)

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[False, False, False],
       [False, False, False]])>

In [40]:
A = tf.reshape(tf.constant(range(3)), (3,1))
B = tf.reshape(tf.constant(range(2)), (1,2))
A, B

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]])>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]])>)

In [41]:
A + B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]])>

In [10]:
x = tf.reshape(tf.Variable(range(4), dtype=tf.float32),(4,1))
x
with tf.GradientTape() as t:
    t.watch(x)
    y = 2 * tf.matmul(tf.transpose(x), x)

dy_dx = t.gradient(y, x)
dy_dx

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [2.],
       [3.]], dtype=float32)>

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 0.],
       [ 4.],
       [ 8.],
       [12.]], dtype=float32)>

In [11]:
num_inputs = 2
num_examples = 10
true_w = [2, -3.4]
true_b = 4.2
features = tf.random.normal((num_examples, num_inputs),stddev = 1)
labels = true_w[0] * features[:,0] + true_w[1] * features[:,1] + true_b
labels += tf.random.normal(labels.shape,stddev=0.01)

In [49]:
labels
features

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 3.8727005,  0.89677  ,  9.143688 , 11.355401 ,  2.3602047,
       -1.0669812,  5.4471054,  5.368192 ,  1.5357974,  8.12541  ],
      dtype=float32)>

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[-0.8956817 , -0.43194982],
       [-0.8602409 ,  0.46082136],
       [-0.6058036 , -1.805441  ],
       [ 0.6556553 , -1.7178956 ],
       [ 0.27836624,  0.7067582 ],
       [-2.0516095 ,  0.34098402],
       [-1.9760023 , -1.5280902 ],
       [ 1.1340685 ,  0.31914675],
       [-0.18065251,  0.6739042 ],
       [-0.13529207, -1.228528  ]], dtype=float32)>

In [12]:
import random

def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    random.shuffle(indices)
    for i in range(0, num_examples, batch_size):
        j = indices[i: min(i+batch_size, num_examples)]
        yield tf.gather(features, axis=0, indices=j), tf.gather(labels, axis=0, indices=j)
        
batch_size = 3
for X, y in data_iter(batch_size, features, labels):
    print(X, y)
    break

tf.Tensor(
[[ 0.5117359 -1.1596843]
 [ 0.7284457  0.2696536]
 [ 1.1353389  1.0366373]], shape=(3, 2), dtype=float32) tf.Tensor([9.178039  4.746102  2.9417982], shape=(3,), dtype=float32)


In [13]:
w = tf.Variable(tf.random.normal((num_inputs, 1), stddev=0.01))
b = tf.Variable(tf.zeros((1,)))

def linreg(X, w, b):
    return tf.matmul(X, w) + b

def squared_loss(y_hat, y):
    return (y_hat - tf.reshape(y, y_hat.shape)) ** 2 /2