# Scipy
scipy 中有许多科学计算常见问题的工具，比如内置了图像处理， 优化，统计等等相关问题的子模块。

https://github.com/jayleicn/scipy-lecture-notes-zh-CN/releases

In [13]:
%config ZMQInteractiveShell.ast_node_interactivity='all'

In [14]:
import os
def get_file_path(filename):
    return os.path.join('./data-dir', filename) 

# 文件输入输出: scipy.io

## 载入和保存matlab文件

In [3]:
from scipy import io as spio

filename = get_file_path('file.mat')
a = np.ones((3, 3))
spio.savemat(filename, {'a': a}) # 保存一个字典到文件

data = spio.loadmat(filename, struct_as_record=True) # 读取mat文件
data['a']

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 读取图像

In [6]:
# from scipy import misc

filename = get_file_path('fname.png')
# misc.imread(filename) # 返回array

# Matplotlib中有一个相似的函数
import matplotlib.pyplot as plt
arr = plt.imread(filename)


** 参见 ** : <br/>
载入文本文件: numpy.loadtxt()/numpy.savetxt() <br/>
格式化载入text/csv文件: numpy.genfromtxt()/numpy.recfromcsv() <br/>
高效快速载入numpy指定类型的，二进制格式文件: numpy.save()/numpy.load() <br/>

# 特殊函数: scipy.special

# 线性代数操作: scipy.linalg
scipy.linalg 模块提供了基于BLAS和LAPACK的高效的代数操作方法

## scipy.linalg.det() 计算方阵的行列式

In [8]:
from scipy import linalg

arr = np.array([[1, 2],
                [3, 4]])
linalg.det(arr)


# linalg.det(np.ones((3, 4))) # ValueError

-2.0

## scipy.linalg.inv() 计算方阵的逆矩阵:

In [18]:
arr = np.array([[1, 2],
                [3, 4]])

iarr = linalg.inv(arr)
iarr

np.allclose(np.dot(arr, iarr), np.eye(2)) # 验证

# 如果计算奇异矩阵(其行列式为0)的逆矩阵，函数会抛出 LinAlgError:
arr = np.array([[3, 2],
               [6, 4]])
# linalg.inv(arr)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

True

## 奇异值分解(SVD)

In [26]:
arr = np.arange(9).reshape((3, 3)) + np.diag([1, 0, 1])
arr
uarr, spec, vharr = linalg.svd(arr)
uarr, spec, vharr

# 原始的矩阵可以使用 svd 的输出结果和 np.dot 的乘积重新生成
svd_mat = uarr.dot(np.diag(spec)).dot(vharr)
np.allclose(svd_mat, arr)

array([[1, 1, 2],
       [3, 4, 5],
       [6, 7, 9]])

(array([[-0.1617463 , -0.98659196,  0.02178164],
        [-0.47456365,  0.09711667,  0.87484724],
        [-0.86523261,  0.13116653, -0.48390895]]),
 array([14.88982544,  0.45294236,  0.29654967]),
 array([[-0.45513179, -0.54511245, -0.70406496],
        [ 0.20258033,  0.70658087, -0.67801525],
        [-0.86707339,  0.45121601,  0.21115836]]))

True

# 快速傅里叶变换: scipy.fftpack
scipy.fftpack 模块包含了快速傅里叶变换的功能.

In [40]:
# 下面是一个噪声信号的例子

time_step = 0.02
period = 5.
time_vec = np.arange(0, 20, time_step)
sig = np.sin(2 * np.pi / period * time_vec) + 0.5 * np.random.randn(time_vec.size)


# 观察者不知道信号的频率，只知道信号的采样间隙time_step; 
# sig信号是来自真实函数的，那么 傅里叶变换是对称的。 
# scipy.fftpack.fftfreq() 函数会生成采样频率，scipy.fftpack.fft() 则用于进行快速傅里叶变化

from scipy import fftpack
sample_freq = fftpack.fftfreq(sig.size, d=time_step)
sig_fft = fftpack.fft(sig)

pidxs = np.where(sample_freq > 0)
freqs = sample_freq[pidxs]
power = np.abs(sig_fft)[pidxs]

# 信号频率可通过如下方式获得:
freq = freqs[power.argmax()]
np.allclose(freq, 1./period)

# import numpy as np
# import pylab as pl
# pl.figure()
# pl.plot(freqs, power)
# pl.xlabel('Frequency [Hz]')
# pl.ylabel('plower')
# axes = pl.axes([0.3, 0.3, 0.5, 0.5])
# pl.title('Peak frequency')
# pl.plot(freqs[:8], power[:8])
# pl.setp(axes, yticks=[])


# 滤去傅里叶变化后的信号中的高频噪声:
sig_fft[np.abs(sample_freq) > freq] = 0

# 去噪后信号可通过如下方式计算： scipy.fftpack.ifft() function:
main_sig = fftpack.ifft(sig_fft)

# pl.figure()
# pl.plot(time_vec, sig)
# pl.plot(time_vec, main_sig, linewidth=3)
# pl.xlabel('Time [s]')
# pl.ylabel('Amplitude')

True

# 优化和拟合: scipy.optimize


# 统计和随机数: scipy.stats

# 插值计算: scipy.interpolate

# Numerical integration: scipy.integrate

# 信号处理: scipy.signal

# 图像处理: scipy.ndimage