参考: https://www.numpy.org.cn/index.html

In [ ]:
import numpy as np 

# NumPy 中的数组

In [ ]:
my_array = np.array([1, 2, 3, 4, 5]) 
my_array

* afdaf
 dafda 
* afda
 afadf 
* dafd
 df

In [ ]:
# 数组的形状
my_array.shape

In [ ]:
# 通过索引访问元素
my_array[0]

In [ ]:
# 通过索引修改元素
my_array[0] = -1
my_array

In [ ]:
# np.zeros()创建一个形状为(５，)的0值数组
my_new_array = np.zeros((5)) 
my_new_array

In [ ]:
# np.zeros()创建一个形状为(５，2)的数组
my_new_array2 = np.zeros((5,2)) 
my_new_array2

In [ ]:
# np.ones()创建一个形状为(５，)的1值数组
my_new_array1 = np.ones((5)) 
my_new_array1

In [ ]:
my_random_array = np.random.random((5))
my_random_array

In [ ]:
# 产生一个二维数组
my_2d_array = np.zeros((2, 3)) 
my_2d_array

In [ ]:
# 产生一个２行４列的矩阵
my_2d_array_new = np.ones((2, 4)) 
my_2d_array_new

In [ ]:
# 访问二维数组元素
my_array = np.array([[1, 2], [3, 4], [5, 6]])
my_array[0][1]

In [ ]:
my_array[0][1] = 10
my_array

In [ ]:
# 取my_array的第１列的所有元素
my_array_column_2 = my_array[:, 1] 
my_array_column_2

In [ ]:
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 取my_array的第１列的[0,2)元素; 行索引以范围的形式给出
my_array_column1_part = my_array[0:2, 1] 
my_array_column1_part

In [ ]:
my_array

In [ ]:
# 取my_array的(第0行,第1列)和(第2行,第1列)的元素; 行索引以枚举的形式给出
my_array_column1_part = my_array[[0,2], 1] 
my_array_column1_part

In [ ]:
# 取my_array的(第0行,第1列)和(第2行,第0列)的元素; 行列索引均以枚举的形式给出,元素位置由行列索引交叉确定
my_array_column_part = my_array[[0,2], [1,0]] 
my_array_column_part

## Numpy中的数组操作

In [ ]:
a = np.array([[1.0, 2.0], [3.0, 4.0]]) 
b = np.array([[5.0, 6.0], [7.0, 8.0]]) 
print('a=\n', a, '\n\nb=\n', b, '\n\n')

#对应元素相加
sum = a + b 
print('a+b=\n', sum, '\n\n')

#对应元素相减
difference = a - b 
print('a-b=\n', difference, '\n\n')

#对应元素相乘
product = a * b
print('a*b=\n', product, '\n\n')

#对应元素相除
quotient = a / b 
print('a/b=\n', quotient, '\n\n')

#对应元素平方
pow2 = a ** 2
print('a**2=\n', pow2, '\n\n')

#对应元素比较
aLessb = a < b
print('a<b=\n', aLessb, '\n\n')

In [ ]:
# 矩阵乘
matrix_product = a.dot(b) 
print('a.dot(b)=\n', matrix_product, '\n\n')

## 创建数组

In [ ]:
# 1D Array
a = np.array([0, 1, 2, 3, 4, 5])
b = np.array((0, 1, 2, 3, 4, 5))
c = np.arange(5)
d = np.linspace(0, 2*np.pi, 5) #将[0, 2*np.pi]分成５份

print(a) 
print(b) 
print(c) 
print(d) 
print(a[3]) 

In [ ]:
# MD Array,
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])

print(a[2,4])
print(a[2][4])

In [ ]:
a2 = np.array([[[11, 12], 
               [13, 14, 15]],
              [[16, 17], 
               [18, 19, 20]],
              [[21, 22], 
               [23, 24, 25]],
              [[26, 27], 
               [28 ,29, 30]],
              [[31, 32], 
               [33, 34, 35]]])
print(a2.shape)
print(a2[2, 1][2])
print(a2[2][1][2])

## 多维数组切片

In [ ]:
#print(a)

print(a[0, 1:4])  #取第０行，第[1,4)列的元素
print(a[1:4, 0])  #取第[1,4)行,第０列的元素
print(a[::2,::2]) #按步长2取[0, maxRows]行,步长2取[0,maxLoc]列的元素
print(a[:, 1])    #取第1列的所有元素

## 数组属性

In [ ]:
# Array properties
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])

print(type(a)) 
print(a.dtype) 
print(a.size)  
print(a.shape) 
print(a.itemsize) 
print(a.ndim)     
print(a.nbytes)   

## 数组函数

In [ ]:
a = np.arange(10)

print(a)
print(a.sum()) 
print(a.min()) 
print(a.max()) 
print(a.cumsum()) # 累加前面所有项

## 数组索引

In [ ]:
a = np.arange(0, 100, 10)
print(a)

In [ ]:
#单一索引    --访问特定元素
print(a[0])
print(a[-1])

In [ ]:
#切片(范围索引) --访问指定范围内的元素
print(a[0:8])
print(a[0:8:2])
print(a[-1:-11:-1])

In [ ]:
#枚举索引， 是获取数组中我们想要的特定元素的有效方法
indices = [1, 5, -1]
b = a[indices] #表示要获取第索引为1,5,-1的元素
print(b)
print(a[[1, 5,-1]]) #相当于以枚举的方式指定要获取元素的索引

In [ ]:
#布尔屏蔽(掩码)
maskIndex = [False ,True, False, False, False, True, False, False, False, True]
print(a[maskIndex])

In [ ]:
#布尔屏蔽(掩码)
import matplotlib.pyplot as plt

x = np.linspace(0, 2*np.pi, 50) #在[0, 2π]中取50个值
y = np.sin(x)
plt.plot(x, y)

mask = (y >= 0)
plt.plot(x[mask], y[mask], 'bo')

mask = (y >= 0) & (x <= np.pi / 2)
plt.plot(x[mask], y[mask], 'go')
plt.show()

## Where 函数
where() 函数是一个根据条件返回数组中的值的有效方法。只需要把条件传递给它，它就会返回一个使得条件为真的元素的列表

In [ ]:
# Where
a = np.arange(0, 100, 10)
a1 = np.where(a < 50) 

print(a1)
print(a1[0])


In [ ]:
# np.where(cond,x,y)满足条件cond输出x，不满足输出y

my_array = np.array([[0, 1, 2],
                     [3, 4, 5],
                     [6, 7, 8]])

my_array = np.where(my_array<5, my_array, 100) #条件cond将作用于my_array的每个元素
print(my_array)



np.where([[True, False], [True, True]], #为True的元素人第二个参数中取,为False的元素从第三个参数中取，　
         [[1111, 22222], [3333, 4444]], 
         [[6666, 77777], [8888, 9999]]) 

In [ ]:
#np.where(arry)：输出arry中真值（非零值）的坐标
where1 = np.where([0, 1, 2])
print(where1, '\n\n')

where2 = np.where([[0, 1, 2], [3, 4, 5]])
print(where2, '\n\n')

# print(where2, '\n\n')输出说明：
# array([0, 0, 1, 1, 1], dtype=int64), 
# array([1, 2, 0, 1, 2], dtype=int64)
# 两组array组成了非零值的坐标. 第一个array[ ]是横坐标，第二个array[ ]是纵坐标；

## Python

In [ ]:
# 快速排速  -- 与C语言的快速排序相比,不用进行元素的移动,操作过程更明了
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot] #得到所有小于pivot的元素
    middle = [x for x in arr if x == pivot] 
    right = [x for x in arr if x > pivot] #得到所有大于pivot的元素
    return quicksort(left) + middle + quicksort(right) #一次快速排序操作(将小于pivot的元素放在左侧，大于pivot的元素放在右侧)

print(quicksort([3,6,8,10,1,2,1]))
# Prints "[1, 1, 2, 3, 6, 8, 10]"

Booleans(布尔类型)
Python实现了所有常用的布尔逻辑运算符，但它使用的是英文单词(and or not ...)而不是符号 (&&, ||, etc.)

In [ ]:
# String
s = "hello"
print(s.capitalize())  # 大写第一个字母 ---"Hello"
print(s.upper())       # 转换成大写 --- "HELLO"
print(s.rjust(7))      # 右对齐, 使用空格填充 --- "  hello"
print(s.center(7))     # 居中对齐, 使用空格填充" hello "
print(s.replace('l', '(ell)'))  # 将'l'字符串替换成'(ell)'  --- "he(ell)(ell)o"
print('  world '.strip())  # 剥去前导和尾部空格 --- "world"

In [ ]:
# 列表推导式
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

In [ ]:
# 列表推导还可以包含条件：

nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)  # Prints "[0, 4, 16]"

In [ ]:
# 字典推导式
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x**2 for x in nums if x%2 == 0}
print(even_num_to_square) 

In [ ]:
# 集合(Sets)
# 集合是不同元素的无序集合

# 遍历集合的语法与遍历列表的语法相同；但是，由于集合是无序的，因此不能假设访问集合元素的顺序：
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))

In [ ]:
# 集合推导式
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print(nums)

# Numpy

## Numpy数组创建

In [ ]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

In [ ]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

## Numpy数组索引
+  数组的切片是对相同数据的视图，因此修改它将修改原始数组。

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 取[0,2)行,[1,3)列区域中的元素:
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# 数组的切片是对相同数据的视图，因此修改它将修改原始数组。
print(a[0, 1])   # 取第0行,第1列中的元素．　Prints "2"
b[0, 0] = 77     # b[0,0] 即 a[0, 1]
print(a[0, 1])   # Prints "77"

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 两种访问数组中间行数据的方法。
# 将整数索引与切片混合会产生较低等级的数组，
# 而仅使用切片会产生与原始数组相同等级的数组：
row_r1 = a[1, :]    # Rank 1 第二行的视图 -- 因为行使用的是整数索引,所以得到的row_r1相对与a是低一维的
row_r2 = a[1:2, :]  # Rank 2 第二行的视图 -- row_r2与a是相同维度的
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# 访问数组的列时，我们可以做出相同的区分： 
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

### 整数数组索引
使用切片索引到numpy数组时，生成的数组视图将始终是原始数组的子数组。 相反，整数数组索引允许你使用另一个数组中的数据构造任意数组

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# 取数组a的(第0行,第0列),(第1行,第1列),(第2行,第0列)的元素; 行列索引均以枚举的形式给出,元素位置由行列索引交叉确定
print(a[[0, 1, 2], [0, 1, 0]])  # -- "[1 4 5]"

# 上面的整数数组索引示例等效于
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# 使用整数数组索引时，可以重用源数组中的相同元素
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# a[[0, 0], [1, 1]]等效于
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

In [ ]:
# 整数数组索引的一个有用技巧是从矩阵的每一行中选择或改变一个元素

import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# 创建索引数组
b = np.array([0, 2, 0, 1])

aRowNum = a.shape[0]

# 使用b中的索引从a的每一行中选择一个元素
print(a[np.arange(aRowNum), b])  # Prints "[ 1  6  7 11]"

# 使用b中的索引来变换a的每一行中的一个元素
a[np.arange(aRowNum), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

In [ ]:
np.arange(4)

In [ ]:
a.shape[0]

### 布尔数组索引
布尔数组索引允许你选择数组的任意元素。通常，这种类型的索引用于选择满足某些条件的数组元素

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])


# 找到大于2的元素;
# 这会返回一个与a形状相同的布尔阵列，其中bool_idx的每个槽都会告诉a的元素是否大于2。
bool_idx = (a > 2)   

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# 我们使用布尔数组索引来构造一个1维数组，该数组由对应于bool_idx的True值的元素组成
print(a[bool_idx])  # Prints "[3 4 5 6]"

# 我们可以在一个简洁的声明中完成上述所有操作
print(a[a > 2])     # Prints "[3 4 5 6]"

## 数据类型
+ numpy数组的所有元素都是相同类型的。Numpy提供了一组可用于构造数组的数据类型。
+ 我们可以在创建数组时让Numpy猜测数据类型，也可以在构造数组时显式指定数据类型。

In [ ]:
import numpy as np

x = np.array([1, 2])   # 让Numpy猜测数据类型
print(x.dtype)         

x = np.array([1.0, 2.0])   # 让Numpy猜测数据类型
print(x.dtype)    

x = np.array([1, 2], dtype=np.int64)   # 强制使用特定的数据类型
print(x.dtype)        

## 数组中的数学

基本数学函数在数组上以元素方式运行，既可以作为运算符重载，也可以作为numpy模块中的函数

In [3]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# 元素和
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# 元素差
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# 元素积
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# 元素除
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# 元素开方
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

# 元素平方
print(np.power(x, 2))
print(x * x)

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[ 1.  4.]
 [ 9. 16.]]
[[ 1.  4.]
 [ 9. 16.]]


Numpy中'*'是元素乘法，而不是矩阵乘法。 Numpy使用dot函数来计算向量的内积。

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# 向量内积
print(v.dot(w))      #面向对象的调用方式
print(np.dot(v, w))  #面向过程的调用方式

# 矩阵与向量的积; 得到一个一维数组 -- [29 67]
print(x.dot(v))
print(np.dot(x, v))

# 矩阵与矩阵的积; 得到一个二维数组
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

### Numpy为在数组上执行计算提供了许多有用的函数

https://www.numpy.org.cn/reference/routines/math.html

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  
print(np.sum(x, axis=0))  # 计算每列的总和; prints "[4 6]"
print(np.sum(x, axis=1))  # 计算每行的总和; prints "[3 7]"

### 操作数组的函数
https://www.numpy.org.cn/reference/routines/array_manipulation_routines.html

In [ ]:
# 转置
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# 请注意，一维数组的转置与原数组相同
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

## 广播(Broadcasting)
广播是一种强大的机制，它允许numpy在执行算术运算时使用不同形状的数组.

将两个数组一起广播遵循以下规则：
1. 如果数组不具有相同的rank，则将较低等级数组的形状添加1，直到两个形状具有相同的长度。
2. 如果两个数组在维度上具有相同的大小，或者如果其中一个数组在该维度中的大小为1，则称这两个数组在维度上是兼容的。
3. 如果数组在所有维度上兼容，则可以一起广播。
4. 广播之后，每个阵列的行为就好像它的形状等于两个输入数组的形状的元素最大值。
5. 在一个数组的大小为1且另一个数组的大小大于1的任何维度中，第一个数组的行为就像沿着该维度复制一样


In [ ]:
np.reshape(v, (1, 3))

### 不使用广播实现向矩阵的每一行添加一个常数向量

In [ ]:
np.array([1, 2, 3]) + np.array([1, 0, 1])

In [ ]:
# 向矩阵的每一行添加一个常数向量

import numpy as np

# 我们将向量v添加到矩阵x的每一行，将结果存储在矩阵y中
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # 创建一个与x形状相同的空矩阵

# 使用显式循环将向量v添加到矩阵x的每一行
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

# 这种方式可以实现效果; 但是当矩阵 x 非常大时，在Python中计算显式循环可能会很慢

注意: 向矩阵x的每一行添加向量v等同于通过垂直堆叠多个v副本来形成矩阵vv，然后对x和vv执行元素的求和。

In [ ]:
import numpy as np

# 我们将向量v添加到矩阵x的每一行，将结果存储在矩阵y中
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # 将v复制4行1列
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # 对x和vv执行元素求和
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

### 使用广播

In [ ]:
# Numpy广播允许我们在不实际创建v的多个副本的情况下执行此计算

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  #使用广播将v添加到x的每一行
print(y)  

In [ ]:
# 广播的一些应用：

import numpy as np

# 计算向量的外积
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# 为了计算外积，我们首先将v重塑为(3, 1)的列向量， 
# 然后我们可以对w广播它以产生形状（3,2）的输出
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# 向矩阵的每一行添加一个向量
x = np.array([[1,2,3], [4,5,6]])

# x具有形状(2,3)，v具有形状(3，)，因此将v广播到(2,3)，给出以下矩阵:
# [[2 4 6]
#  [5 7 9]]
print(x + v)


# 向矩阵的每列添加向量. x具有形状(2,3),并且w具有形状(2，)。 
# 我们先转置x, x.T具有形状(3,2),对w广播以产生形状(3,2); 
# 最后将结果再转置回来即实现按列添加：
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# 另一种解决方案是将w重塑为形状(2,1)的列向量; 然后我们可以直接对x广播它以产生相同的输出。
print(x + np.reshape(w, (2, 1)))

# 将矩阵乘以常数：x具有形状（2,3）。 Numpy将标量视为shape()数组; 这些可以一起广播成形(2,3)，产生以下数组:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

In [ ]:
v = np.array([1,2,3])
v

In [ ]:
np.reshape(v, (3, 1))